version: "3"

services:

    rabbitmq:
        image: rabbitmq:3-management
        container_name: rabbit-nerdstore
        environment:
            RABBITMQ_DEFAULT_USER: "nerdstore"
            RABBITMQ_DEFAULT_PASS: "nerdstore"

    sql-server:
        image: nerdstore-sql-server:latest
        container_name: nerdstore-sql-server
        build: 
            context: ../sql
            dockerfile: ./Dockerfile
        environment:
            SA_PASSWORD: "MeuDB@123"
            ACCEPT_EULA: "Y"     

    web-mvc:
        image: nerdstore-web-mvc-ecommerce:latest
        # container_name: nerdstore-web-mvc-ecommerce
        build:
            context: ../src
            dockerfile: ./web/NSE.WebApp/Dockerfile
        restart: always
        environment:
            - ASPNETCORE_ENVIRONMENT=Production
            - ASPNETCORE_URLS=http://*:5001
        volumes:
            - dpkeys:/var/data_protection_keys/
        depends_on:
            - api-catalogo
            - api-identidade
            - api-cliente
            - api-bff-compras

    api-identidade:
        image: nerdstore-api-identidade:latest
        container_name: nerdstore-api-identidade
        build:
            context: ../src
            dockerfile: ./services/NSE.Identidade/Dockerfile
        restart: always
        environment:
            - ASPNETCORE_ENVIRONMENT=Production
            - ASPNETCORE_URLS=https://+:5101;http://+5101
            - ASPNETCORE_Kestrel__Certificates__Default__Password=nerdstore
            - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/nerdstore-certificate.pfx
        volumes:
             - ./certs:/https:ro
        depends_on:
            - rabbitmq

    api-carrinho:
        image: nerdstore-api-carrinho:latest
        container_name: nerdstore-api-carrinho
        build:
            context: ../src
            dockerfile: ./services/NSE.Carrinho/Dockerfile
        restart: always
        environment:
            - ASPNETCORE_ENVIRONMENT=Production
            - ASPNETCORE_URLS=https://+:5201;http://+5201
            - ASPNETCORE_Kestrel__Certificates__Default__Password=nerdstore
            - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/nerdstore-certificate.pfx
        volumes:
             - ./certs:/https:ro
        depends_on:
            - rabbitmq
            - api-identidade

    api-catalogo:
        image: nerdstore-api-catalogo:latest
        container_name: nerdstore-api-catalogo
        build:
            context: ../src
            dockerfile: ./services/NSE.Catalogo/Dockerfile
        restart: always
        environment:
            - ASPNETCORE_ENVIRONMENT=Production
            - ASPNETCORE_URLS=https://+:5301;http://+5301
            - ASPNETCORE_Kestrel__Certificates__Default__Password=nerdstore
            - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/nerdstore-certificate.pfx
        volumes:
             - ./certs:/https:ro
        depends_on:
            - rabbitmq

    api-cliente:
        image: nerdstore-api-cliente:latest
        container_name: nerdstore-api-cliente
        build:
            context: ../src
            dockerfile: ./services/NSE.Clientes/Dockerfile
        restart: always
        environment:
            - ASPNETCORE_ENVIRONMENT=Production
            - ASPNETCORE_URLS=https://+:5401;http://+5401
            - ASPNETCORE_Kestrel__Certificates__Default__Password=nerdstore
            - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/nerdstore-certificate.pfx
        volumes:
             - ./certs:/https:ro
        depends_on:
            - rabbitmq
            - api-identidade

    api-bff-compras:
        image: nerdstore-api-bff-compras:latest
        container_name: nerdstore-api-bff-compras
        build:
            context: ../src
            dockerfile: ./api gateways/NSE.Bff.Compras/Dockerfile
        restart: always
        environment:
            - ASPNETCORE_ENVIRONMENT=Production
            - ASPNETCORE_URLS=https://+:5501;http://+5501
            - ASPNETCORE_Kestrel__Certificates__Default__Password=nerdstore
            - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/nerdstore-certificate.pfx
        volumes:
             - ./certs:/https:ro
        depends_on:
            - rabbitmq
            - api-identidade
            - api-carrinho
            - api-pagamento
            - api-pedido

    api-pagamento:
        image: nerdstore-api-pagamento:latest
        container_name: nerdstore-api-pagamento
        build:
            context: ../src
            dockerfile: ./services/NSE.Pagamentos/Dockerfile
        restart: always
        environment:
            - ASPNETCORE_ENVIRONMENT=Production
            - ASPNETCORE_URLS=https://+:5601;http://+5601
            - ASPNETCORE_Kestrel__Certificates__Default__Password=nerdstore
            - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/nerdstore-certificate.pfx
        volumes:
             - ./certs:/https:ro
        depends_on:
            - rabbitmq
            - api-identidade
            - api-pedido

    api-pedido:
        image: nerdstore-api-pedido:latest
        container_name: nerdstore-api-pedido
        build:
            context: ../src
            dockerfile: ./services/NSE.Pedidos/Dockerfile
        restart: always
        environment:
            - ASPNETCORE_ENVIRONMENT=Production
            - ASPNETCORE_URLS=https://+:5701;http://+5701
            - ASPNETCORE_Kestrel__Certificates__Default__Password=nerdstore
            - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/nerdstore-certificate.pfx
        volumes:
             - ./certs:/https:ro
        depends_on:
            - rabbitmq
            - api-identidade

    nerdstore-server:
        image: nerdstore-server:latest
        container_name: nerdstore-server
        build:
            context: ./
            dockerfile: ./nginx/Dockerfile
        restart: always
        ports:
            - "80:80"
            - "443:443"
        depends_on:
            - web-mvc

volumes:
    dpkeys: